#!/usr/bin/env bash
# Stage03: destructive storage preparation.
#
# This is the single user-facing storage entrypoint. It destroys the selected
# target disk, creates the final GPT layout, initializes LUKS2, creates Btrfs,
# mounts the final layout under /mnt, and writes complete state/storage.env.

set -euo pipefail

STAGE03_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STAGE03_LIB_DIR="${STAGE03_DIR}/lib"
STAGE03_STATE_DIR="${STAGE03_STATE_DIR:-${STAGE03_DIR}/../state}"
STAGE03_STORAGE_STATE_FILE="${STAGE03_STORAGE_STATE_FILE:-${STAGE03_STATE_DIR}/storage.env}"
STAGE03_TARGET_ROOT="${STAGE03_TARGET_ROOT:-/mnt}"
STAGE03_TARGET_INSTALL_STATE_FILE="${STAGE03_TARGET_INSTALL_STATE_FILE:-${STAGE03_TARGET_ROOT}/root/install-state.env}"

# shellcheck source=lib/common.sh
source "${STAGE03_LIB_DIR}/common.sh"
# shellcheck source=lib/logging.sh
source "${STAGE03_LIB_DIR}/logging.sh"
# shellcheck source=lib/config.sh
source "${STAGE03_LIB_DIR}/config.sh"
# shellcheck source=lib/hardware.sh
source "${STAGE03_LIB_DIR}/hardware.sh"
# shellcheck source=lib/disk-common.sh
source "${STAGE03_LIB_DIR}/disk-common.sh"
# shellcheck source=lib/disk-partition.sh
source "${STAGE03_LIB_DIR}/disk-partition.sh"
# shellcheck source=lib/disk-luks.sh
source "${STAGE03_LIB_DIR}/disk-luks.sh"
# shellcheck source=lib/disk-btrfs.sh
source "${STAGE03_LIB_DIR}/disk-btrfs.sh"

trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

STAGE03_TARGET_DISK=""
STAGE03_EFI_PARTITION=""
STAGE03_LUKS_PARTITION=""
STAGE03_LUKS_UUID=""
STAGE03_MAPPED_DEVICE=""
STAGE03_BTRFS_UUID=""
STAGE03_DESTRUCTIVE_CONFIRMED="no"

require_arch_live_iso() {
  require_arch_live_or_arch

  [[ -d /run/archiso ]] || \
    die "Stage03 debe ejecutarse desde el Arch Linux Live ISO oficial."
}

require_stage03_commands() {
  require_command \
    awk \
    blkid \
    btrfs \
    cryptsetup \
    findmnt \
    lsblk \
    mkfs.btrfs \
    mkfs.fat \
    mount \
    partprobe \
    realpath \
    sfdisk \
    sleep \
    stat \
    udevadm \
    umount \
    wipefs \
    chown
}

load_stage03_existing_storage_state_for_target_disk() {
  local state_file="${STAGE03_STORAGE_STATE_FILE}"
  local resolved_state
  local resolved_state_dir
  local state_target_disk

  [[ -n "${TARGET_DISK:-}" ]] && return 0
  [[ -r "${state_file}" ]] || return 0

  validate_absolute_path "${state_file}"
  resolved_state="$(realpath -m -- "${state_file}")"
  resolved_state_dir="$(realpath -m -- "${STAGE03_STATE_DIR}")"

  [[ "${resolved_state}" == "${resolved_state_dir}/"* ]] || \
    die "Archivo de estado fuera de state/: ${resolved_state}"

  # storage.env is trusted project state generated by this installer. At this
  # point only TARGET_DISK is useful; storage UUIDs will be regenerated below.
  state_target_disk="$(
    # shellcheck source=/dev/null
    source "${resolved_state}"
    printf '%s\n' "${TARGET_DISK:-}"
  )"
  [[ -n "${state_target_disk}" ]] || return 0
  TARGET_DISK="${state_target_disk}"
}

resolve_stage03_target_disk() {
  load_stage03_existing_storage_state_for_target_disk
  [[ -n "${TARGET_DISK:-}" ]] || die "TARGET_DISK no esta configurado. Ejecuta Stage02 antes de Stage03."
  STAGE03_TARGET_DISK="$(resolve_disk_realpath "${TARGET_DISK}")"
  export TARGET_DISK="${STAGE03_TARGET_DISK}"
}

validate_stage03_target_disk() {
  if ! hardware_disk_in_inventory "${STAGE03_TARGET_DISK}"; then
    die "El disco seleccionado ya no esta disponible en el inventario actual: ${STAGE03_TARGET_DISK}"
  fi

  validate_target_disk "${STAGE03_TARGET_DISK}"
}

ensure_stage03_mountpoints_are_free() {
  if is_mounted "${STAGE03_TARGET_ROOT}"; then
    die "${STAGE03_TARGET_ROOT} ya esta montado. Desmonta manualmente antes de ejecutar Stage03."
  fi

  if is_mounted "${STAGE03_TARGET_ROOT}/boot"; then
    die "${STAGE03_TARGET_ROOT}/boot ya esta montado. Desmonta manualmente antes de ejecutar Stage03."
  fi

  if path_has_mount_under "${STAGE03_TARGET_ROOT}"; then
    log_warn "Se detectaron montajes bajo ${STAGE03_TARGET_ROOT}:"
    findmnt -R "${STAGE03_TARGET_ROOT}" || true
    die "Desmonta manualmente los montajes hijos bajo ${STAGE03_TARGET_ROOT} antes de ejecutar Stage03."
  fi
}

show_stage03_plan() {
  log_section "Plan destructivo Stage03"
  hardware_show_disk_details "${STAGE03_TARGET_DISK}"
  hardware_warn_if_removable_disk "${STAGE03_TARGET_DISK}"
  hardware_warn_if_live_iso_disk "${STAGE03_TARGET_DISK}"
  hardware_warn_if_disk_has_mounts "${STAGE03_TARGET_DISK}"
  log_kv "Disco a destruir" "${STAGE03_TARGET_DISK}"
  log_kv "Particion EFI" "$(efi_partition "${STAGE03_TARGET_DISK}")"
  log_kv "Particion LUKS" "$(luks_partition "${STAGE03_TARGET_DISK}")"
  log_kv "Mapper LUKS" "$(mapper_path "${CRYPT_NAME}")"
  log_kv "Subvolumen" "@ -> ${STAGE03_TARGET_ROOT}"
  log_kv "Subvolumen" "@home -> ${STAGE03_TARGET_ROOT}/home"
  log_kv "Subvolumen" "@var -> ${STAGE03_TARGET_ROOT}/var"
  log_kv "Subvolumen" "@snapshots -> ${STAGE03_TARGET_ROOT}/.snapshots"
}

confirm_stage03_destructive_operation() {
  confirm_destructive_disk_action "${STAGE03_TARGET_DISK}"
  STAGE03_DESTRUCTIVE_CONFIRMED="yes"
}

require_stage03_destructive_confirmation() {
  [[ "${STAGE03_DESTRUCTIVE_CONFIRMED}" == "yes" ]] || \
    die "Accion destructiva bloqueada: falta confirmacion exacta del disco."
}

prepare_stage03_partitions() {
  require_stage03_destructive_confirmation
  log_section "Particionado destructivo"
  wipe_previous_filesystem_signatures "${STAGE03_TARGET_DISK}"
  wipe_previous_partition_signatures_if_needed "${STAGE03_TARGET_DISK}"
  create_empty_gpt_table "${STAGE03_TARGET_DISK}"
  reload_kernel_partition_table "${STAGE03_TARGET_DISK}" 0
  verify_empty_gpt_table "${STAGE03_TARGET_DISK}"
  create_final_gpt_partition_layout "${STAGE03_TARGET_DISK}" "${EFI_SIZE}"
  wait_for_final_partition_layout "${STAGE03_TARGET_DISK}"
  verify_final_partition_layout "${STAGE03_TARGET_DISK}" "${EFI_SIZE}"
  show_partition_table "${STAGE03_TARGET_DISK}"
  show_block_identifiers "${STAGE03_TARGET_DISK}"

  STAGE03_EFI_PARTITION="$(efi_partition "${STAGE03_TARGET_DISK}")"
  STAGE03_LUKS_PARTITION="$(luks_partition "${STAGE03_TARGET_DISK}")"
}

format_stage03_efi() {
  require_stage03_destructive_confirmation
  log_section "EFI"
  format_efi_fat32 "${STAGE03_EFI_PARTITION}"
}

create_and_open_stage03_luks() {
  require_stage03_destructive_confirmation
  log_section "LUKS2"
  require_luks_partition_ready_for_format "${STAGE03_TARGET_DISK}" "${EFI_SIZE}" "${CRYPT_NAME}"
  format_luks2_container "${STAGE03_LUKS_PARTITION}"
  STAGE03_LUKS_UUID="$(luks_uuid "${STAGE03_LUKS_PARTITION}")"
  open_luks_container "${STAGE03_LUKS_PARTITION}" "${CRYPT_NAME}"
  verify_open_luks_container "${STAGE03_LUKS_PARTITION}" "${CRYPT_NAME}"
  STAGE03_MAPPED_DEVICE="$(mapper_path "${CRYPT_NAME}")"
  show_luks_diagnostics "${STAGE03_LUKS_PARTITION}" "${CRYPT_NAME}"
}

install_stage03_cleanup_trap() {
  trap 'cleanup_btrfs_mountpoint_on_failure "${STAGE03_TARGET_ROOT}/boot"; cleanup_btrfs_mounts_on_failure "${STAGE03_TARGET_ROOT}"; cleanup_luks_mapper_on_failure "${CRYPT_NAME}"; on_error "$LINENO" "$BASH_COMMAND"' ERR
}

restore_stage03_default_error_trap() {
  trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR
}

create_and_mount_stage03_btrfs() {
  log_section "Btrfs"
  create_directory "${STAGE03_TARGET_ROOT}"
  create_btrfs "${STAGE03_MAPPED_DEVICE}" "${BTRFS_LABEL}"
  STAGE03_BTRFS_UUID="$(btrfs_uuid "${STAGE03_MAPPED_DEVICE}")"
  create_btrfs_subvolumes "${STAGE03_MAPPED_DEVICE}" "${STAGE03_TARGET_ROOT}"
  mount_btrfs_subvolumes "${STAGE03_MAPPED_DEVICE}" "${STAGE03_TARGET_ROOT}"
  mount_stage03_efi
  verify_stage03_mount_layout
}

mount_stage03_efi() {
  local boot_mount="${STAGE03_TARGET_ROOT}/boot"

  create_directory "${boot_mount}"
  if is_mounted "${boot_mount}"; then
    die "${boot_mount} ya esta montado inesperadamente."
  fi

  log_step "Montando particion EFI en ${boot_mount}"
  mount "${STAGE03_EFI_PARTITION}" "${boot_mount}"
}

verify_stage03_mount_layout() {
  local boot_fstype

  verify_btrfs_subvolume_mounts "${STAGE03_TARGET_ROOT}"
  boot_fstype="$(findmnt -no FSTYPE --target "${STAGE03_TARGET_ROOT}/boot" 2>/dev/null || true)"
  case "${boot_fstype}" in
    vfat|fat|msdos) ;;
    *) die "${STAGE03_TARGET_ROOT}/boot no esta montado como FAT/VFAT." ;;
  esac
  show_btrfs_mount_summary "${STAGE03_TARGET_ROOT}"
  success "Layout final montado correctamente."
}

write_stage03_storage_state() {
  create_directory "${STAGE03_STATE_DIR}" 0700

  write_file_atomic "${STAGE03_STORAGE_STATE_FILE}" <<EOF
# Generated by scripts/stage03-storage.sh.
TARGET_DISK=$(printf '%q' "${STAGE03_TARGET_DISK}")
EFI_PARTITION=$(printf '%q' "${STAGE03_EFI_PARTITION}")
LUKS_PARTITION=$(printf '%q' "${STAGE03_LUKS_PARTITION}")
CRYPT_NAME=$(printf '%q' "${CRYPT_NAME}")
MAPPED_DEVICE=$(printf '%q' "${STAGE03_MAPPED_DEVICE}")
LUKS_UUID=$(printf '%q' "${STAGE03_LUKS_UUID}")
BTRFS_UUID=$(printf '%q' "${STAGE03_BTRFS_UUID}")
TARGET_ROOT=$(printf '%q' "${STAGE03_TARGET_ROOT}")
BTRFS_LABEL=$(printf '%q' "${BTRFS_LABEL}")
BTRFS_COMPRESS=$(printf '%q' "${BTRFS_COMPRESS}")
EFI_SIZE=$(printf '%q' "${EFI_SIZE}")
EOF
  chmod 0600 "${STAGE03_STORAGE_STATE_FILE}"
  require_readable_file "${STAGE03_STORAGE_STATE_FILE}"
}

write_stage03_target_install_state() {
  local state_file="${STAGE03_TARGET_INSTALL_STATE_FILE}"

  validate_absolute_path "${state_file}"
  [[ "${state_file}" == "${STAGE03_TARGET_ROOT%/}/root/install-state.env" ]] || \
    die "Ruta de estado target inesperada: ${state_file}"

  create_directory "${STAGE03_TARGET_ROOT}/root" 0700

  write_file_atomic "${state_file}" <<EOF
# Generated by scripts/stage03-storage.sh.
TARGET_ROOT=$(printf '%q' "${STAGE03_TARGET_ROOT}")
TARGET_DISK=$(printf '%q' "${STAGE03_TARGET_DISK}")
EFI_PARTITION=$(printf '%q' "${STAGE03_EFI_PARTITION}")
LUKS_PARTITION=$(printf '%q' "${STAGE03_LUKS_PARTITION}")
CRYPT_NAME=$(printf '%q' "${CRYPT_NAME}")
MAPPED_DEVICE=$(printf '%q' "${STAGE03_MAPPED_DEVICE}")
LUKS_UUID=$(printf '%q' "${STAGE03_LUKS_UUID}")
BTRFS_UUID=$(printf '%q' "${STAGE03_BTRFS_UUID}")
BTRFS_LABEL=$(printf '%q' "${BTRFS_LABEL}")
BTRFS_COMPRESS=$(printf '%q' "${BTRFS_COMPRESS}")
EFI_SIZE=$(printf '%q' "${EFI_SIZE}")
HOSTNAME=$(printf '%q' "${HOSTNAME}")
USERNAME=$(printf '%q' "${USERNAME}")
TIMEZONE=$(printf '%q' "${TIMEZONE}")
LOCALE=$(printf '%q' "${LOCALE}")
KEYMAP=$(printf '%q' "${KEYMAP}")
ENABLE_SECURE_BOOT=$(printf '%q' "${ENABLE_SECURE_BOOT:-no}")
SBCTL_CREATE_KEYS=$(printf '%q' "${SBCTL_CREATE_KEYS:-yes}")
SBCTL_ENROLL_MICROSOFT_KEYS=$(printf '%q' "${SBCTL_ENROLL_MICROSOFT_KEYS:-no}")
INSTALL_DESKTOP_ENV=$(printf '%q' "${INSTALL_DESKTOP_ENV:-none}")
EOF
  chown 0:0 "${state_file}"
  chmod 0600 "${state_file}"
  require_readable_file "${state_file}"
}

verify_stage03_target_install_state() {
  local state_file="${STAGE03_TARGET_INSTALL_STATE_FILE}"
  local mode
  local owner

  require_readable_file "${state_file}"
  mode="$(stat -c '%a' "${state_file}")"
  owner="$(stat -c '%u:%g' "${state_file}")"

  [[ "${mode}" == "600" ]] || die "${state_file} debe tener permisos 600; permisos actuales: ${mode}"
  [[ "${owner}" == "0:0" ]] || die "${state_file} debe pertenecer a root:root; owner actual: ${owner}"
}

persist_stage03_install_state_contract() {
  log_step "Escribiendo contrato persistente del instalador en ${STAGE03_TARGET_INSTALL_STATE_FILE}"
  write_stage03_target_install_state
  verify_stage03_target_install_state
  success "Contrato persistente del instalador disponible para Stage06/07/08."
}

show_stage03_summary() {
  log_section "Resumen Stage03"
  log_kv "Target disk" "${STAGE03_TARGET_DISK}"
  log_kv "EFI partition" "${STAGE03_EFI_PARTITION}"
  log_kv "LUKS partition" "${STAGE03_LUKS_PARTITION}"
  log_kv "LUKS UUID" "${STAGE03_LUKS_UUID}"
  log_kv "Mapper" "${STAGE03_MAPPED_DEVICE}"
  log_kv "Btrfs UUID" "${STAGE03_BTRFS_UUID}"
  log_kv "Mount root" "${STAGE03_TARGET_ROOT}"
  log_kv "Estado" "${STAGE03_STORAGE_STATE_FILE}"
  log_kv "Estado target" "${STAGE03_TARGET_INSTALL_STATE_FILE}"
  success "Stage03 completado. El almacenamiento esta preparado y montado; Stage04 puede continuar."
}

main() {
  log_section "Stage03 - almacenamiento destructivo"
  require_root
  require_arch_live_iso
  require_uefi
  require_stage03_commands

  log_step "Cargando configuracion"
  load_install_config
  validate_install_config
  success "Configuracion cargada y validada."

  log_step "Actualizando inventario de discos"
  hardware_refresh_disk_inventory
  [[ "$(hardware_disk_count)" -gt 0 ]] || die "No se detectaron discos instalables."

  resolve_stage03_target_disk
  validate_stage03_target_disk
  ensure_stage03_mountpoints_are_free
  show_stage03_plan
  confirm_stage03_destructive_operation

  install_stage03_cleanup_trap
  prepare_stage03_partitions
  format_stage03_efi
  create_and_open_stage03_luks
  create_and_mount_stage03_btrfs
  restore_stage03_default_error_trap

  write_stage03_storage_state
  persist_stage03_install_state_contract
  show_stage03_summary
}

main "$@"
