#!/usr/bin/env bash
# Stage05: configure Secure Boot in the installed target using sbctl.
#
# This stage manages sbctl keys, enrollment, signing and verification for the
# already installed Arch target. It does not partition, format, install
# packages, configure NVIDIA, configure desktop/hardening, or run Stage06.

set -euo pipefail

STAGE05_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STAGE05_LIB_DIR="${STAGE05_DIR}/lib"
STAGE05_TARGET_ROOT="${STAGE05_TARGET_ROOT:-/mnt}"
STAGE05_INSTALL_STATE_FILE="${STAGE05_INSTALL_STATE_FILE:-${STAGE05_TARGET_ROOT}/root/install-state.env}"

# shellcheck source=lib/common.sh
source "${STAGE05_LIB_DIR}/common.sh"
# shellcheck source=lib/logging.sh
source "${STAGE05_LIB_DIR}/logging.sh"
# shellcheck source=lib/config.sh
source "${STAGE05_LIB_DIR}/config.sh"
# shellcheck source=lib/hardware.sh
source "${STAGE05_LIB_DIR}/hardware.sh"
# shellcheck source=lib/chroot.sh
source "${STAGE05_LIB_DIR}/chroot.sh"
# shellcheck source=lib/secureboot.sh
source "${STAGE05_LIB_DIR}/secureboot.sh"
# shellcheck source=lib/bootloader.sh
source "${STAGE05_LIB_DIR}/bootloader.sh"

trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

require_arch_live_iso() {
  require_arch_live_or_arch

  [[ -d /run/archiso ]] || \
    die "Stage05 debe ejecutarse desde el Arch Linux Live ISO oficial."
}

load_stage05_install_state() {
  local state_file="${STAGE05_INSTALL_STATE_FILE}"
  local resolved_state
  local target_root_real

  validate_absolute_path "${state_file}"
  resolved_state="$(realpath -m -- "${state_file}")"
  target_root_real="$(realpath -m -- "${STAGE05_TARGET_ROOT}")"

  [[ "${resolved_state}" == "${target_root_real}/root/install-state.env" ]] || \
    die "Archivo de estado inesperado: ${resolved_state}"
  require_readable_file "${resolved_state}"

  # install-state.env is trusted shell state generated by Stage03.
  # shellcheck source=/dev/null
  source "${resolved_state}"

  require_variable LUKS_UUID
  require_variable BTRFS_UUID
  require_variable EFI_PARTITION
  require_variable LUKS_PARTITION
  require_variable CRYPT_NAME
  require_variable MAPPED_DEVICE

  TARGET_ROOT="${STAGE05_TARGET_ROOT}"
  export TARGET_ROOT LUKS_UUID BTRFS_UUID EFI_PARTITION LUKS_PARTITION CRYPT_NAME MAPPED_DEVICE
}

validate_stage05_target() {
  validate_arch_target_root "${STAGE05_TARGET_ROOT}"
  require_directory "$(target_path "${STAGE05_TARGET_ROOT}" /boot)"
  is_mounted "$(target_path "${STAGE05_TARGET_ROOT}" /boot)" || \
    die "/mnt/boot no esta montado."
  require_target_sbctl "${STAGE05_TARGET_ROOT}"
}

show_stage05_status() {
  show_secureboot_status_summary "${STAGE05_TARGET_ROOT}"
}

enable_bootloader_auto_signing() {
  local target_root="${STAGE05_TARGET_ROOT}"

  log_section "Firma automatica del bootloader"
  BOOTLOADER_SIGN_AFTER_REGEN="yes"
  export BOOTLOADER_SIGN_AFTER_REGEN

  regenerate_systemd_boot_entries "${target_root}"
  install_bootloader_regeneration_hook "${target_root}"
}

verify_stage05_secureboot() {
  local target_root="${STAGE05_TARGET_ROOT}"

  log_section "Verificacion Secure Boot"
  log_step "Ejecutando sbctl status"
  arch_chroot_run "${target_root}" sbctl status
  verify_secureboot_signatures "${target_root}"
}

show_stage05_summary() {
  log_section "Resumen final Stage05"
  log_kv "Target root" "${STAGE05_TARGET_ROOT}"
  log_kv "Secure Boot" "$(secureboot_status)"
  log_kv "Setup Mode" "$(detect_setup_mode)"
  log_kv "Firma bootloader post-regeneracion" "${BOOTLOADER_SIGN_AFTER_REGEN}"
  success "Stage05 completado. Stage06 no se ejecutara automaticamente."
}

main() {
  log_section "Stage05 - Secure Boot"
  require_root
  require_arch_live_iso
  require_uefi

  log_step "Cargando configuracion"
  load_install_config
  validate_install_config
  success "Configuracion cargada y validada."

  log_step "Cargando estado del target"
  load_stage05_install_state
  validate_stage05_target

  show_stage05_status
  create_sbctl_keys_if_enabled "${STAGE05_TARGET_ROOT}"
  enroll_sbctl_keys_conservative "${STAGE05_TARGET_ROOT}"
  enable_bootloader_auto_signing
  sign_secureboot_artifacts "${STAGE05_TARGET_ROOT}"
  install_secureboot_hooks "${STAGE05_TARGET_ROOT}"
  verify_stage05_secureboot
  show_secureboot_bios_instructions
  show_stage05_summary
}

main "$@"
