#!/usr/bin/env bash
# Legacy Stage03 bootstrap: install the Arch base system into /mnt.
#
# This stage installs packages with pacstrap, generates fstab, writes crypttab,
# and copies minimal installer state into the target. It does not partition,
# format, configure users, configure hostname/locale, install a bootloader,
# configure Secure Boot, configure NVIDIA, or run the next stage.
#
# Order requirement: scripts/stage03-storage.sh must run first. It creates the
# partitions, LUKS2 container, Btrfs filesystem, final /mnt mounts, and complete
# state/storage.env consumed here.

set -euo pipefail

STAGE03_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STAGE03_LIB_DIR="${STAGE03_DIR}/lib"
STAGE03_TARGET_ROOT="${STAGE03_TARGET_ROOT:-/mnt}"
STAGE03_STATE_DIR="${STAGE03_STATE_DIR:-${STAGE03_DIR}/../state}"
STAGE03_STORAGE_STATE_FILE="${STAGE03_STORAGE_STATE_FILE:-${STAGE03_STATE_DIR}/storage.env}"
STAGE03_PACKAGES_FILE="${STAGE03_PACKAGES_FILE:-${STAGE03_STATE_DIR}/packages-final.txt}"
STAGE03_TARGET_DISK="${STAGE03_TARGET_DISK:-}"

# shellcheck source=lib/common.sh
source "${STAGE03_LIB_DIR}/common.sh"
# shellcheck source=lib/logging.sh
source "${STAGE03_LIB_DIR}/logging.sh"
# shellcheck source=lib/config.sh
source "${STAGE03_LIB_DIR}/config.sh"
# shellcheck source=lib/hardware.sh
source "${STAGE03_LIB_DIR}/hardware.sh"
# shellcheck source=lib/packages.sh
source "${STAGE03_LIB_DIR}/packages.sh"
# shellcheck source=lib/disk.sh
source "${STAGE03_LIB_DIR}/disk.sh"
# shellcheck source=lib/chroot.sh
source "${STAGE03_LIB_DIR}/chroot.sh"

trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

require_arch_live_iso() {
  require_arch_live_or_arch

  [[ -d /run/archiso ]] || \
    die "Stage03 debe ejecutarse desde el Arch Linux Live ISO oficial."
}

require_stage03_commands() {
  require_command pacstrap genfstab findmnt cryptsetup blkid chown
}

load_stage03_storage_state() {
  local state_file="${STAGE03_STORAGE_STATE_FILE}"
  local resolved_state
  local resolved_state_dir

  validate_absolute_path "${state_file}"
  resolved_state="$(realpath -m -- "${state_file}")"
  resolved_state_dir="$(realpath -m -- "${STAGE03_STATE_DIR}")"

  [[ "${resolved_state}" == "${resolved_state_dir}/"* ]] || \
    die "Archivo de estado fuera de state/: ${resolved_state}"
  [[ -r "${resolved_state}" ]] || \
    die "Ejecuta scripts/stage03-storage.sh antes de este bootstrap. Falta estado: ${resolved_state}"

  # storage.env is trusted shell state generated by Stage02.
  # shellcheck source=/dev/null
  source "${resolved_state}"

  require_variable LUKS_UUID
  require_variable BTRFS_UUID
  require_variable MAPPED_DEVICE
  require_variable EFI_PARTITION
  require_variable LUKS_PARTITION
  require_variable CRYPT_NAME

  STAGE03_TARGET_DISK="${TARGET_DISK:-}"
  require_variable STAGE03_TARGET_DISK
}

validate_stage03_storage_state() {
  log_section "Validacion de almacenamiento"

  require_directory "${STAGE03_TARGET_ROOT}"
  is_mounted "${STAGE03_TARGET_ROOT}" || die "${STAGE03_TARGET_ROOT} no esta montado."

  [[ "$(findmnt -no FSTYPE --target "${STAGE03_TARGET_ROOT}" 2>/dev/null || true)" == "btrfs" ]] || \
    die "${STAGE03_TARGET_ROOT} no esta montado como Btrfs."
  success "${STAGE03_TARGET_ROOT} montado como Btrfs."

  [[ "$(findmnt -no FSTYPE --target "${STAGE03_TARGET_ROOT}/boot" 2>/dev/null || true)" == "vfat" ]] || \
    die "${STAGE03_TARGET_ROOT}/boot no esta montado como vfat."
  success "${STAGE03_TARGET_ROOT}/boot montado como vfat."

  [[ -b "${MAPPED_DEVICE}" ]] || die "MAPPED_DEVICE no existe o no es bloque: ${MAPPED_DEVICE}"
  cryptsetup status "${CRYPT_NAME}" >/dev/null 2>&1 || \
    die "Mapper LUKS no abierto o no reconocido por cryptsetup: ${CRYPT_NAME}"
  success "Mapper LUKS abierto: ${MAPPED_DEVICE}"

  [[ -b "${EFI_PARTITION}" ]] || die "EFI_PARTITION no existe o no es bloque: ${EFI_PARTITION}"
  [[ -b "${LUKS_PARTITION}" ]] || die "LUKS_PARTITION no existe o no es bloque: ${LUKS_PARTITION}"
  [[ "$(cryptsetup luksUUID "${LUKS_PARTITION}")" == "${LUKS_UUID}" ]] || \
    die "LUKS_UUID no coincide con ${LUKS_PARTITION}."
  [[ "$(blkid -s UUID -o value "${MAPPED_DEVICE}")" == "${BTRFS_UUID}" ]] || \
    die "BTRFS_UUID no coincide con ${MAPPED_DEVICE}."
}

write_final_package_list() {
  create_directory "${STAGE03_STATE_DIR}" 0700
  build_package_list | write_file_atomic "${STAGE03_PACKAGES_FILE}"
  require_readable_file "${STAGE03_PACKAGES_FILE}"
  validate_saved_package_list_not_empty
}

validate_saved_package_list_not_empty() {
  local count

  count="$(awk 'NF { count++ } END { print count + 0 }' "${STAGE03_PACKAGES_FILE}")"
  [[ "${count}" -gt 0 ]] || die "La lista final de paquetes esta vacia: ${STAGE03_PACKAGES_FILE}"
}

show_stage03_package_summary() {
  local count

  count="$(awk 'NF { count++ } END { print count + 0 }' "${STAGE03_PACKAGES_FILE}")"
  log_section "Paquetes a instalar"
  log_kv "Archivo" "${STAGE03_PACKAGES_FILE}"
  log_kv "Total" "${count}"
  while IFS= read -r package_name; do
    [[ -n "${package_name}" ]] || continue
    log_kv "Paquete" "${package_name}"
  done < "${STAGE03_PACKAGES_FILE}"
}

confirm_pacstrap_install() {
  confirm_yes_no "Deseas instalar el sistema base en ${STAGE03_TARGET_ROOT} con pacstrap?" || \
    die "Stage03 abortado limpiamente antes de ejecutar pacstrap."
}

install_base_system() {
  log_section "Pacstrap"
  pacstrap_install_package_list "${STAGE03_TARGET_ROOT}" "${STAGE03_PACKAGES_FILE}"
}

write_target_fstab() {
  local target_root="${STAGE03_TARGET_ROOT}"
  local fstab
  local tmp
  local old_return_trap

  fstab="$(target_path "${target_root}" /etc/fstab)"
  require_directory "$(dirname -- "${fstab}")"

  tmp="$(mktemp)"
  old_return_trap="$(trap -p RETURN || true)"
  trap 'rm -f -- "${tmp}"' RETURN

  log_step "Generando fstab con genfstab -U"
  genfstab -U "${target_root}" > "${tmp}"
  [[ -s "${tmp}" ]] || die "genfstab no genero contenido."

  if [[ -e "${fstab}" ]]; then
    backup_file "${fstab}"
  fi
  write_file_atomic "${fstab}" < "${tmp}"
  rm -f -- "${tmp}"

  if [[ -n "${old_return_trap}" ]]; then
    eval "${old_return_trap}"
  else
    trap - RETURN
  fi
}

write_target_crypttab() {
  local target_root="${STAGE03_TARGET_ROOT}"
  local crypttab

  crypttab="$(target_path "${target_root}" /etc/crypttab)"
  require_directory "$(dirname -- "${crypttab}")"

  if [[ -e "${crypttab}" ]]; then
    backup_file "${crypttab}"
  fi

  write_file_atomic "${crypttab}" <<EOF
${CRYPT_NAME} UUID=${LUKS_UUID} none luks
EOF
  chmod 0644 "${crypttab}"
}

write_target_install_state() {
  local target_root="${STAGE03_TARGET_ROOT}"
  local state_file

  state_file="$(target_path "${target_root}" /root/install-state.env)"
  require_directory "$(dirname -- "${state_file}")"

  write_file_atomic "${state_file}" <<EOF
# Generated by scripts/stage03-bootstrap.sh.
TARGET_DISK=$(printf '%q' "${STAGE03_TARGET_DISK}")
EFI_PARTITION=$(printf '%q' "${EFI_PARTITION}")
LUKS_PARTITION=$(printf '%q' "${LUKS_PARTITION}")
CRYPT_NAME=$(printf '%q' "${CRYPT_NAME}")
MAPPED_DEVICE=$(printf '%q' "${MAPPED_DEVICE}")
LUKS_UUID=$(printf '%q' "${LUKS_UUID}")
BTRFS_UUID=$(printf '%q' "${BTRFS_UUID}")
TARGET_ROOT=$(printf '%q' "${STAGE03_TARGET_ROOT}")
BTRFS_LABEL=$(printf '%q' "${BTRFS_LABEL}")
BTRFS_COMPRESS=$(printf '%q' "${BTRFS_COMPRESS}")
EFI_SIZE=$(printf '%q' "${EFI_SIZE}")
HOSTNAME=$(printf '%q' "${HOSTNAME}")
USERNAME=$(printf '%q' "${USERNAME}")
TIMEZONE=$(printf '%q' "${TIMEZONE}")
LOCALE=$(printf '%q' "${LOCALE}")
KEYMAP=$(printf '%q' "${KEYMAP}")
ENABLE_SECURE_BOOT=$(printf '%q' "${ENABLE_SECURE_BOOT:-no}")
SBCTL_CREATE_KEYS=$(printf '%q' "${SBCTL_CREATE_KEYS:-yes}")
SBCTL_ENROLL_MICROSOFT_KEYS=$(printf '%q' "${SBCTL_ENROLL_MICROSOFT_KEYS:-no}")
INSTALL_DESKTOP_ENV=$(printf '%q' "${INSTALL_DESKTOP_ENV:-none}")
PACKAGES_FILE=$(printf '%q' "${STAGE03_PACKAGES_FILE}")
EOF
  chown 0:0 "${state_file}"
  chmod 0600 "${state_file}"
}

show_stage03_summary() {
  log_section "Resumen final Stage03"
  log_kv "Target root" "${STAGE03_TARGET_ROOT}"
  log_kv "Paquetes" "${STAGE03_PACKAGES_FILE}"
  log_kv "fstab" "$(target_path "${STAGE03_TARGET_ROOT}" /etc/fstab)"
  log_kv "crypttab" "$(target_path "${STAGE03_TARGET_ROOT}" /etc/crypttab)"
  log_kv "Estado target" "$(target_path "${STAGE03_TARGET_ROOT}" /root/install-state.env)"
  success "Stage03 completado. Stage04 no se ejecutara automaticamente."
}

main() {
  log_section "Stage03 - Bootstrap"
  require_root
  require_arch_live_iso
  require_uefi
  require_stage03_commands

  log_step "Cargando configuracion"
  load_install_config
  validate_install_config
  success "Configuracion cargada y validada."

  log_step "Cargando estado de almacenamiento"
  load_stage03_storage_state
  validate_stage03_storage_state

  log_step "Construyendo lista final de paquetes"
  write_final_package_list
  show_stage03_package_summary
  confirm_pacstrap_install

  install_base_system
  write_target_fstab
  write_target_crypttab
  write_target_install_state
  validate_arch_target_root "${STAGE03_TARGET_ROOT}"
  show_stage03_summary
}

main "$@"
