#!/usr/bin/env bash
# Stage07: passive hardening checks for the installed Arch target.
#
# This stage is intentionally conservative and idempotent. It does not install
# packages or write hardening configuration. The only active changes allowed by
# this stage are enabling apparmor.service and nftables.service when those units
# already exist in the target.

set -euo pipefail

STAGE07_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STAGE07_LIB_DIR="${STAGE07_DIR}/lib"
STAGE07_TARGET_ROOT="${STAGE07_TARGET_ROOT:-/mnt}"
STAGE07_INSTALL_STATE_FILE="${STAGE07_INSTALL_STATE_FILE:-${STAGE07_TARGET_ROOT}/root/install-state.env}"
STAGE07_PASS_COUNT=0
STAGE07_WARN_COUNT=0
STAGE07_FAIL_COUNT=0
STAGE07_RESULTS=()

# shellcheck source=lib/common.sh
source "${STAGE07_LIB_DIR}/common.sh"
# shellcheck source=lib/logging.sh
source "${STAGE07_LIB_DIR}/logging.sh"
# shellcheck source=lib/config.sh
source "${STAGE07_LIB_DIR}/config.sh"
# shellcheck source=lib/chroot.sh
source "${STAGE07_LIB_DIR}/chroot.sh"
# shellcheck source=lib/hardware.sh
source "${STAGE07_LIB_DIR}/hardware.sh"

trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

require_arch_live_iso() {
  require_arch_live_or_arch

  [[ -d /run/archiso ]] || \
    die "Stage07 debe ejecutarse desde el Arch Linux Live ISO oficial."
}

load_stage07_install_state() {
  local state_file="${STAGE07_INSTALL_STATE_FILE}"
  local resolved_state
  local target_root_real

  validate_absolute_path "${state_file}"
  resolved_state="$(realpath -m -- "${state_file}")"
  target_root_real="$(realpath -m -- "${STAGE07_TARGET_ROOT}")"

  [[ "${resolved_state}" == "${target_root_real}/root/install-state.env" ]] || \
    die "Archivo de estado inesperado: ${resolved_state}"
  require_readable_file "${resolved_state}"

  # install-state.env is trusted shell state generated by Stage03.
  # shellcheck source=/dev/null
  source "${resolved_state}"

  TARGET_ROOT="${STAGE07_TARGET_ROOT}"
  export TARGET_ROOT
}

stage07_record() {
  local level="$1"
  local message="$2"

  STAGE07_RESULTS+=("${level}|${message}")
  case "${level}" in
    PASS)
      STAGE07_PASS_COUNT=$((STAGE07_PASS_COUNT + 1))
      success "[PASS] ${message}"
      ;;
    WARN)
      STAGE07_WARN_COUNT=$((STAGE07_WARN_COUNT + 1))
      log_warn "[WARN] ${message}"
      ;;
    FAIL)
      STAGE07_FAIL_COUNT=$((STAGE07_FAIL_COUNT + 1))
      log_error "[FAIL] ${message}"
      ;;
    *)
      die "Nivel de resultado invalido: ${level}"
      ;;
  esac
}

stage07_pass() {
  stage07_record "PASS" "$1"
}

stage07_warn() {
  stage07_record "WARN" "$1"
}

stage07_fail() {
  stage07_record "FAIL" "$1"
}

target_file_exists_stage07() {
  local path="$1"

  validate_absolute_path "${path}"
  [[ -e "$(target_path "${STAGE07_TARGET_ROOT}" "${path}")" ]]
}

target_command_exists_stage07() {
  local command_name="$1"

  [[ "${command_name}" =~ ^[A-Za-z0-9_.+-]+$ ]] || die "Comando invalido: ${command_name}"
  arch_chroot_run "${STAGE07_TARGET_ROOT}" command -v "${command_name}" >/dev/null 2>&1
}

target_unit_exists_stage07() {
  local unit="$1"

  validate_systemd_unit_name "${unit}"
  [[ -e "$(target_path "${STAGE07_TARGET_ROOT}" "/etc/systemd/system/${unit}")" ]] ||
    [[ -e "$(target_path "${STAGE07_TARGET_ROOT}" "/usr/lib/systemd/system/${unit}")" ]] ||
    [[ -e "$(target_path "${STAGE07_TARGET_ROOT}" "/lib/systemd/system/${unit}")" ]]
}

target_service_enabled_stage07() {
  local unit="$1"

  validate_systemd_unit_name "${unit}"
  arch_chroot_run "${STAGE07_TARGET_ROOT}" systemctl is-enabled "${unit}" >/dev/null 2>&1
}

enable_existing_service_stage07() {
  local label="$1"
  local unit="$2"

  if ! target_unit_exists_stage07 "${unit}"; then
    stage07_warn "${label}: ${unit} no existe; no se habilita."
    return 0
  fi

  if enable_target_service "${STAGE07_TARGET_ROOT}" "${unit}" >/dev/null 2>&1; then
    stage07_pass "${label}: ${unit} habilitado."
  else
    stage07_fail "${label}: no se pudo habilitar ${unit}."
  fi
}

verify_existing_service_stage07() {
  local label="$1"
  local unit="$2"

  if ! target_unit_exists_stage07 "${unit}"; then
    stage07_warn "${label}: ${unit} no existe."
    return 0
  fi

  if target_service_enabled_stage07 "${unit}"; then
    stage07_pass "${label}: ${unit} habilitado."
  else
    stage07_warn "${label}: ${unit} existe pero no esta habilitado."
  fi
}

detect_setup_mode_stage07() {
  local setup_mode_var
  local byte

  if ! is_uefi_booted; then
    printf 'unsupported\n'
    return 0
  fi

  setup_mode_var="$(find /sys/firmware/efi/efivars -maxdepth 1 -name 'SetupMode-*' -print -quit 2>/dev/null || true)"
  if [[ -z "${setup_mode_var}" || ! -r "${setup_mode_var}" ]]; then
    printf 'unknown\n'
    return 0
  fi

  byte="$(od -An -t u1 -j 4 -N 1 "${setup_mode_var}" 2>/dev/null | tr -d '[:space:]' || true)"
  case "${byte}" in
    1) printf 'enabled\n' ;;
    0) printf 'disabled\n' ;;
    *) printf 'unknown\n' ;;
  esac
}

check_stage07_apparmor() {
  log_section "AppArmor"
  if target_command_exists_stage07 apparmor_parser || target_unit_exists_stage07 apparmor.service; then
    enable_existing_service_stage07 "AppArmor" "apparmor.service"
  else
    stage07_warn "AppArmor no parece instalado."
  fi
}

check_stage07_nftables() {
  log_section "nftables"
  if target_command_exists_stage07 nft || target_unit_exists_stage07 nftables.service; then
    enable_existing_service_stage07 "nftables" "nftables.service"
    if target_file_exists_stage07 /etc/nftables.conf; then
      stage07_pass "Existe /etc/nftables.conf."
    else
      stage07_warn "No existe /etc/nftables.conf."
    fi
  else
    stage07_warn "nft no parece instalado."
  fi
}

check_stage07_static_files() {
  log_section "Archivos de configuracion"

  if target_file_exists_stage07 /etc/systemd/journald.conf; then
    stage07_pass "Existe /etc/systemd/journald.conf."
  else
    stage07_warn "Falta /etc/systemd/journald.conf."
  fi

  if target_command_exists_stage07 sshd; then
    if target_file_exists_stage07 /etc/ssh/sshd_config; then
      stage07_pass "sshd instalado y existe /etc/ssh/sshd_config."
    else
      stage07_warn "sshd instalado, pero falta /etc/ssh/sshd_config."
    fi
  else
    stage07_warn "sshd no parece instalado."
  fi

  if [[ -d "$(target_path "${STAGE07_TARGET_ROOT}" /etc/sysctl.d)" ]]; then
    stage07_pass "Existe /etc/sysctl.d."
  else
    stage07_warn "Falta /etc/sysctl.d."
  fi
}

check_stage07_snapper() {
  log_section "Snapper"
  if target_command_exists_stage07 snapper; then
    if target_file_exists_stage07 /etc/snapper/configs/root; then
      stage07_pass "Snapper instalado y configuracion root existe."
    else
      stage07_warn "Snapper instalado, pero falta /etc/snapper/configs/root."
    fi
  else
    stage07_warn "Snapper no parece instalado."
  fi
}

check_stage07_service_statuses() {
  log_section "Servicios existentes"
  verify_existing_service_stage07 "Reflector" "reflector.timer"
  verify_existing_service_stage07 "fstrim" "fstrim.timer"

  if target_command_exists_stage07 docker || target_unit_exists_stage07 docker.service; then
    verify_existing_service_stage07 "Docker" "docker.service"
  else
    stage07_warn "Docker no parece instalado."
  fi

  if target_command_exists_stage07 virsh || target_unit_exists_stage07 libvirtd.service; then
    verify_existing_service_stage07 "libvirt" "libvirtd.service"
  else
    stage07_warn "libvirt no parece instalado."
  fi

  if target_command_exists_stage07 bluetoothd || target_unit_exists_stage07 bluetooth.service; then
    verify_existing_service_stage07 "Bluetooth" "bluetooth.service"
  else
    stage07_warn "Bluetooth no parece instalado."
  fi

  if target_command_exists_stage07 cupsd || target_unit_exists_stage07 cups.service; then
    verify_existing_service_stage07 "CUPS" "cups.service"
  else
    stage07_warn "CUPS no parece instalado."
  fi

  if target_command_exists_stage07 sddm || target_unit_exists_stage07 sddm.service; then
    verify_existing_service_stage07 "SDDM" "sddm.service"
  else
    stage07_warn "SDDM no parece instalado."
  fi
}

check_stage07_secureboot_status() {
  log_section "Secure Boot"
  stage07_pass "Secure Boot actual: $(detect_secure_boot)"
  stage07_pass "Setup Mode actual: $(detect_setup_mode_stage07)"
}

show_stage07_summary() {
  local entry
  local level
  local message

  log_section "Resumen Stage07"
  log_kv "PASS" "${STAGE07_PASS_COUNT}"
  log_kv "WARN" "${STAGE07_WARN_COUNT}"
  log_kv "FAIL" "${STAGE07_FAIL_COUNT}"

  log_header "Detalle"
  for entry in "${STAGE07_RESULTS[@]}"; do
    level="${entry%%|*}"
    message="${entry#*|}"
    log_kv "${level}" "${message}"
  done

  if [[ "${STAGE07_FAIL_COUNT}" -gt 0 ]]; then
    die "Stage07 finalizo con fallos."
  fi

  success "Stage07 completado. Stage08 no se ejecutara automaticamente."
}

main() {
  log_section "Stage07 - Hardening"
  require_root
  require_arch_live_iso
  require_uefi

  log_step "Cargando configuracion"
  load_install_config
  validate_install_config
  success "Configuracion cargada y validada."

  log_step "Cargando estado del target"
  load_stage07_install_state
  validate_arch_target_root "${STAGE07_TARGET_ROOT}"

  check_stage07_apparmor
  check_stage07_nftables
  check_stage07_static_files
  check_stage07_snapper
  check_stage07_service_statuses
  check_stage07_secureboot_status
  show_stage07_summary
}

main "$@"
