#!/usr/bin/env bash
# Stage04: configure the installed base system inside /mnt.
#
# This stage configures the already bootstrapped Arch target. It does not
# partition, format, install packages, run pacstrap, configure desktop,
# configure hardening, configure Secure Boot, configure NVIDIA, or run Stage05.

set -euo pipefail

STAGE04_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STAGE04_LIB_DIR="${STAGE04_DIR}/lib"
STAGE04_TARGET_ROOT="${STAGE04_TARGET_ROOT:-/mnt}"
STAGE04_INSTALL_STATE_FILE="${STAGE04_INSTALL_STATE_FILE:-${STAGE04_TARGET_ROOT}/root/install-state.env}"

# shellcheck source=lib/common.sh
source "${STAGE04_LIB_DIR}/common.sh"
# shellcheck source=lib/logging.sh
source "${STAGE04_LIB_DIR}/logging.sh"
# shellcheck source=lib/config.sh
source "${STAGE04_LIB_DIR}/config.sh"
# shellcheck source=lib/chroot.sh
source "${STAGE04_LIB_DIR}/chroot.sh"

trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

require_arch_live_iso() {
  require_arch_live_or_arch

  [[ -d /run/archiso ]] || \
    die "Stage04 debe ejecutarse desde el Arch Linux Live ISO oficial."
}

load_stage04_install_state() {
  local state_file="${STAGE04_INSTALL_STATE_FILE}"
  local resolved_state
  local target_root_real

  validate_absolute_path "${state_file}"
  resolved_state="$(realpath -m -- "${state_file}")"
  target_root_real="$(realpath -m -- "${STAGE04_TARGET_ROOT}")"

  [[ "${resolved_state}" == "${target_root_real}/root/install-state.env" ]] || \
    die "Archivo de estado inesperado: ${resolved_state}"
  require_readable_file "${resolved_state}"

  # install-state.env is trusted shell state generated by Stage03.
  # shellcheck source=/dev/null
  source "${resolved_state}"

  require_variable LUKS_UUID
  require_variable BTRFS_UUID
  require_variable EFI_PARTITION
  require_variable LUKS_PARTITION
  require_variable CRYPT_NAME
  require_variable MAPPED_DEVICE

  TARGET_ROOT="${STAGE04_TARGET_ROOT}"
  export TARGET_ROOT LUKS_UUID BTRFS_UUID EFI_PARTITION LUKS_PARTITION CRYPT_NAME MAPPED_DEVICE
}

configure_stage04_base_system() {
  local target_root="${STAGE04_TARGET_ROOT}"

  log_section "Configuracion base del target"
  configure_target_hostname "${target_root}" "${HOSTNAME}"
  configure_target_timezone "${target_root}" "${TIMEZONE}"
  configure_target_locale "${target_root}" "${LOCALE}"
  configure_target_keymap "${target_root}" "${KEYMAP}"
  create_target_user "${target_root}" "${USERNAME}" "wheel" "/bin/bash"
  configure_target_sudo "${target_root}"
  configure_target_mkinitcpio_luks_btrfs "${target_root}"
}

show_stage04_summary() {
  log_section "Resumen final Stage04"
  log_kv "Target root" "${STAGE04_TARGET_ROOT}"
  log_kv "Hostname" "${HOSTNAME}"
  log_kv "Usuario" "${USERNAME}"
  log_kv "Timezone" "${TIMEZONE}"
  log_kv "Locale" "${LOCALE}"
  log_kv "Keymap" "${KEYMAP}"
  log_kv "Crypt name" "${CRYPT_NAME}"
  log_kv "LUKS UUID" "${LUKS_UUID}"
  success "Stage04 completado. Ejecuta Stage05 para instalar/configurar systemd-boot."
}

main() {
  log_section "Stage04 - Base Config"
  require_root
  require_arch_live_iso
  require_uefi

  log_step "Cargando configuracion"
  load_install_config
  validate_install_config
  success "Configuracion cargada y validada."

  log_step "Cargando estado del target"
  load_stage04_install_state
  validate_arch_target_root "${STAGE04_TARGET_ROOT}"

  configure_stage04_base_system
  validate_arch_target_root "${STAGE04_TARGET_ROOT}"
  show_stage04_summary
}

main "$@"
