#!/usr/bin/env bash
# Stage08: final passive verification and closing instructions.
#
# This stage does not modify the installed system. It only verifies the target
# under /mnt, prints a complete summary, and leaves reboot/unmount decisions to
# the operator.

set -euo pipefail

STAGE08_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STAGE08_LIB_DIR="${STAGE08_DIR}/lib"
STAGE08_TARGET_ROOT="${STAGE08_TARGET_ROOT:-/mnt}"
STAGE08_INSTALL_STATE_FILE="${STAGE08_INSTALL_STATE_FILE:-${STAGE08_TARGET_ROOT}/root/install-state.env}"
STAGE08_TARGET_DISK=""

# shellcheck source=lib/common.sh
source "${STAGE08_LIB_DIR}/common.sh"
# shellcheck source=lib/logging.sh
source "${STAGE08_LIB_DIR}/logging.sh"
# shellcheck source=lib/config.sh
source "${STAGE08_LIB_DIR}/config.sh"
# shellcheck source=lib/hardware.sh
source "${STAGE08_LIB_DIR}/hardware.sh"
# shellcheck source=lib/chroot.sh
source "${STAGE08_LIB_DIR}/chroot.sh"
# shellcheck source=lib/secureboot.sh
source "${STAGE08_LIB_DIR}/secureboot.sh"
# shellcheck source=lib/verify.sh
source "${STAGE08_LIB_DIR}/verify.sh"

trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

require_arch_live_iso() {
  require_arch_live_or_arch

  [[ -d /run/archiso ]] || \
    die "Stage08 debe ejecutarse desde el Arch Linux Live ISO oficial."
}

load_stage08_install_state() {
  local state_file="${STAGE08_INSTALL_STATE_FILE}"
  local resolved_state
  local target_root_real

  validate_absolute_path "${state_file}"
  resolved_state="$(realpath -m -- "${state_file}")"
  target_root_real="$(realpath -m -- "${STAGE08_TARGET_ROOT}")"

  [[ "${resolved_state}" == "${target_root_real}/root/install-state.env" ]] || \
    die "Archivo de estado inesperado: ${resolved_state}"
  require_readable_file "${resolved_state}"

  # install-state.env is trusted shell state generated by Stage03.
  # shellcheck source=/dev/null
  source "${resolved_state}"

  require_variable EFI_PARTITION
  require_variable LUKS_PARTITION
  require_variable LUKS_UUID
  require_variable BTRFS_UUID
  require_variable MAPPED_DEVICE
  require_variable CRYPT_NAME

  STAGE08_TARGET_DISK="${TARGET_DISK:-}"
  TARGET_ROOT="${STAGE08_TARGET_ROOT}"
  export TARGET_ROOT LUKS_UUID BTRFS_UUID EFI_PARTITION LUKS_PARTITION MAPPED_DEVICE CRYPT_NAME
}

verify_stage08_mounts_still_present() {
  log_section "Comprobacion de montajes"

  require_directory "${STAGE08_TARGET_ROOT}"
  is_mounted "${STAGE08_TARGET_ROOT}" && verify_pass "/mnt sigue montado" || verify_fail "/mnt no esta montado"
  is_mounted "$(target_path "${STAGE08_TARGET_ROOT}" /boot)" && verify_pass "/mnt/boot sigue montado" || verify_fail "/mnt/boot no esta montado"
  [[ -b "${MAPPED_DEVICE}" ]] && verify_pass "Mapper LUKS accesible: ${MAPPED_DEVICE}" || verify_fail "Mapper LUKS no accesible: ${MAPPED_DEVICE}"
}

verify_stage08_pipewire() {
  if target_command_exists "${STAGE08_TARGET_ROOT}" pipewire; then
    verify_pass "PipeWire instalado"
  else
    verify_warn "PipeWire no instalado"
  fi
}

run_stage08_final_verification() {
  log_section "Verificacion final pasiva"

  if run_passive_verification "${STAGE08_TARGET_ROOT}" "${LUKS_PARTITION}"; then
    log_info "Verificacion pasiva base completada sin FAIL."
  else
    log_warn "La verificacion pasiva base reporto FAIL; se continuara para mostrar resumen final."
  fi

  verify_stage08_pipewire
  verify_stage08_mounts_still_present
}

list_stage08_kernels() {
  local kernel_dir
  local kernel
  local found="no"

  kernel_dir="$(target_path "${STAGE08_TARGET_ROOT}" /boot)"
  for kernel in "${kernel_dir}"/vmlinuz-*; do
    [[ -e "${kernel}" ]] || continue
    found="yes"
    log_kv "Kernel" "${kernel#"${kernel_dir}/"}"
  done

  [[ "${found}" == "yes" ]] || log_kv "Kernel" "no detectado"
}

show_stage08_system_info() {
  local target_hostname

  target_hostname="$(cat "$(target_path "${STAGE08_TARGET_ROOT}" /etc/hostname)" 2>/dev/null || true)"

  log_section "Informacion del sistema"
  log_kv "Hostname" "${target_hostname:-no detectado}"
  log_kv "Usuario principal" "${USERNAME}"
  log_kv "Disco objetivo" "${STAGE08_TARGET_DISK:-no registrado}"
  log_kv "Particion EFI" "${EFI_PARTITION}"
  log_kv "Particion LUKS" "${LUKS_PARTITION}"
  log_kv "UUID LUKS" "${LUKS_UUID}"
  log_kv "UUID Btrfs" "${BTRFS_UUID}"
  log_kv "Mapper" "${MAPPED_DEVICE}"
  list_stage08_kernels
  log_kv "Secure Boot" "$(secureboot_status)"
  log_kv "Setup Mode" "$(detect_setup_mode)"
}

show_stage08_final_instructions() {
  log_section "Instrucciones finales"
  log_info "1. Revisa que no existan errores en el resumen anterior."
  log_info "2. Sal del Live ISO cuando hayas terminado las revisiones."
  log_info "3. Reinicia manualmente el equipo."
  log_info "4. Entra en BIOS/UEFI."
  log_info "5. Activa Secure Boot si aun no esta activado."
  log_info "6. Arranca Arch Linux."
  log_info "7. Ejecuta dentro de Arch:"
  log_info "   sbctl status"
  log_info "   sbctl verify"
  log_info "   systemctl --failed"
  log_info "8. Verifica que no existan unidades fallidas."
}

show_stage08_final_summary() {
  log_section "Resumen final de verificacion"
  log_kv "PASS" "${VERIFY_PASS_COUNT}"
  log_kv "WARN" "${VERIFY_WARN_COUNT}"
  log_kv "FAIL" "${VERIFY_FAIL_COUNT}"

  if [[ "${VERIFY_FAIL_COUNT}" -gt 0 ]]; then
    die "La instalacion tiene verificaciones FAIL. Revisa el resumen antes de reiniciar."
  fi

  log_section "INSTALACION COMPLETADA CORRECTAMENTE"
}

main() {
  log_section "Stage08 - Finalize"
  require_root
  require_arch_live_iso
  require_uefi

  log_step "Cargando configuracion"
  load_install_config
  validate_install_config
  success "Configuracion cargada y validada."

  log_step "Cargando estado del target"
  load_stage08_install_state
  validate_arch_target_root "${STAGE08_TARGET_ROOT}"

  run_stage08_final_verification
  show_stage08_system_info
  show_stage08_final_instructions
  show_stage08_final_summary
}

main "$@"
