#!/usr/bin/env bash
# Stage06: configure installed system services and user integration.
#
# Stage03 already installed all packages. This stage only configures the
# installed target under /mnt. It must not install packages, touch bootloader,
# Secure Boot, NVIDIA, hardening, sysctl, nftables, AppArmor, or run Stage07.

set -euo pipefail

STAGE06_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
STAGE06_LIB_DIR="${STAGE06_DIR}/lib"
STAGE06_TARGET_ROOT="${STAGE06_TARGET_ROOT:-/mnt}"
STAGE06_INSTALL_STATE_FILE="${STAGE06_INSTALL_STATE_FILE:-${STAGE06_TARGET_ROOT}/root/install-state.env}"
STAGE06_ENABLED_SERVICES=()
STAGE06_OMITTED_SERVICES=()
STAGE06_WARNINGS=()

# shellcheck source=lib/common.sh
source "${STAGE06_LIB_DIR}/common.sh"
# shellcheck source=lib/logging.sh
source "${STAGE06_LIB_DIR}/logging.sh"
# shellcheck source=lib/config.sh
source "${STAGE06_LIB_DIR}/config.sh"
# shellcheck source=lib/chroot.sh
source "${STAGE06_LIB_DIR}/chroot.sh"
# shellcheck source=lib/hardware.sh
source "${STAGE06_LIB_DIR}/hardware.sh"

trap 'on_error "$LINENO" "$BASH_COMMAND"' ERR

require_arch_live_iso() {
  require_arch_live_or_arch

  [[ -d /run/archiso ]] || \
    die "Stage06 debe ejecutarse desde el Arch Linux Live ISO oficial."
}

load_stage06_install_state() {
  local state_file="${STAGE06_INSTALL_STATE_FILE}"
  local resolved_state
  local target_root_real

  validate_absolute_path "${state_file}"
  resolved_state="$(realpath -m -- "${state_file}")"
  target_root_real="$(realpath -m -- "${STAGE06_TARGET_ROOT}")"

  [[ "${resolved_state}" == "${target_root_real}/root/install-state.env" ]] || \
    die "Archivo de estado inesperado: ${resolved_state}"
  require_readable_file "${resolved_state}"

  # install-state.env is trusted shell state generated by Stage03.
  # shellcheck source=/dev/null
  source "${resolved_state}"

  TARGET_ROOT="${STAGE06_TARGET_ROOT}"
  export TARGET_ROOT
}

record_enabled_service() {
  STAGE06_ENABLED_SERVICES+=("$1")
}

record_omitted_service() {
  STAGE06_OMITTED_SERVICES+=("$1")
}

record_stage06_warning() {
  STAGE06_WARNINGS+=("$1")
  log_warn "$1"
}

target_command_exists_stage06() {
  local command_name="$1"

  target_command_exists "${STAGE06_TARGET_ROOT}" "${command_name}"
}

stage06_target_group_exists() {
  local group_name="$1"

  validate_shell_identifier "${group_name}" "grupo"
  arch_chroot_run "${STAGE06_TARGET_ROOT}" getent group "${group_name}" >/dev/null 2>&1
}

stage06_target_user_exists() {
  local username="$1"

  validate_username_value "${username}"
  arch_chroot_run "${STAGE06_TARGET_ROOT}" id -u "${username}" >/dev/null 2>&1
}

stage06_target_unit_exists() {
  local unit="$1"

  validate_systemd_unit_name "${unit}"
  [[ -e "$(target_path "${STAGE06_TARGET_ROOT}" "/etc/systemd/system/${unit}")" ]] ||
    [[ -e "$(target_path "${STAGE06_TARGET_ROOT}" "/usr/lib/systemd/system/${unit}")" ]] ||
    [[ -e "$(target_path "${STAGE06_TARGET_ROOT}" "/lib/systemd/system/${unit}")" ]]
}

ensure_stage06_user() {
  local username="${USERNAME}"

  log_section "Usuario"
  validate_username_value "${username}"

  STAGE06_INTERACTIVE_PASSWORDS="${STAGE06_INTERACTIVE_PASSWORDS:-yes}"
  export STAGE06_INTERACTIVE_PASSWORDS
  configure_target_users "${STAGE06_TARGET_ROOT}" "${username}" "wheel audio video storage input network"
}

enable_service_if_available() {
  local label="$1"
  local unit="$2"
  local command_name="${3:-}"

  if stage06_target_unit_exists "${unit}" || { [[ -n "${command_name}" ]] && target_command_exists_stage06 "${command_name}"; }; then
    if enable_target_service "${STAGE06_TARGET_ROOT}" "${unit}"; then
      record_enabled_service "${unit}"
    else
      record_omitted_service "${unit} (error al habilitar)"
      record_stage06_warning "No se pudo habilitar ${label}: ${unit}"
    fi
  else
    record_omitted_service "${unit} (no instalado)"
    log_info "Omitido ${label}: unidad/binario no encontrado."
  fi
}

stage06_enable_required_service() {
  local label="$1"
  local unit="$2"

  if enable_target_service "${STAGE06_TARGET_ROOT}" "${unit}"; then
    record_enabled_service "${unit}"
  else
    record_omitted_service "${unit} (error al habilitar)"
    record_stage06_warning "No se pudo habilitar ${label}: ${unit}"
  fi
}

stage06_networkmanager_available() {
  stage06_target_unit_exists NetworkManager.service || target_command_exists_stage06 NetworkManager
}

configure_stage06_network() {
  log_section "Red"

  if ! is_yes "${INSTALL_NETWORK_PROFILE:-yes}"; then
    record_stage06_warning "Perfil de red desactivado; no se habilita NetworkManager ni systemd-networkd."
    return 0
  fi

  if stage06_networkmanager_available; then
    stage06_enable_required_service "NetworkManager" "NetworkManager.service"
    log_info "NetworkManager instalado; no se configura fallback systemd-networkd."
    return 0
  fi

  log_warn "NetworkManager no esta instalado; se configurara fallback con systemd-networkd y systemd-resolved."
  create_directory "$(target_path "${STAGE06_TARGET_ROOT}" /etc/systemd/network)" 0755
  write_target_file "${STAGE06_TARGET_ROOT}" /etc/systemd/network/20-wired.network <<'EOF'
[Match]
Name=en* eth* ens*

[Network]
DHCP=yes
EOF
  stage06_enable_required_service "systemd-networkd" "systemd-networkd.service"
  stage06_enable_required_service "systemd-resolved" "systemd-resolved.service"
  arch_chroot_run "${STAGE06_TARGET_ROOT}" ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
}

configure_stage06_ssh() {
  log_section "OpenSSH"

  if ! is_yes "${INSTALL_OPENSSH:-yes}"; then
    record_stage06_warning "INSTALL_OPENSSH desactivado; sshd.service no se habilita."
    return 0
  fi

  enable_service_if_available "OpenSSH" "sshd.service" "sshd"
}

configure_stage06_services() {
  log_section "Servicios"
  configure_stage06_network
  configure_stage06_ssh
  enable_service_if_available "Bluetooth" "bluetooth.service" "bluetoothd"
  enable_service_if_available "Docker" "docker.service" "docker"
  enable_service_if_available "libvirt" "libvirtd.service" "virsh"
  enable_service_if_available "SDDM" "sddm.service" "sddm"
  enable_service_if_available "CUPS" "cups.service" "cupsd"
  enable_service_if_available "Reflector" "reflector.timer" "reflector"
  enable_service_if_available "fstrim" "fstrim.timer" "fstrim"
}

add_user_to_group_if_available() {
  local username="$1"
  local group_name="$2"
  local label="$3"

  if stage06_target_group_exists "${group_name}"; then
    arch_chroot_run "${STAGE06_TARGET_ROOT}" usermod -aG "${group_name}" "${username}"
    log_info "${username} agregado a ${group_name} (${label})."
  else
    record_stage06_warning "Grupo no encontrado para ${label}: ${group_name}"
  fi
}

configure_stage06_integrations() {
  log_section "Integraciones"

  if target_command_exists_stage06 docker; then
    add_user_to_group_if_available "${USERNAME}" docker "Docker"
  else
    log_info "Docker no instalado; no se modifica grupo docker."
  fi

  if target_command_exists_stage06 virsh || target_command_exists_stage06 libvirtd; then
    add_user_to_group_if_available "${USERNAME}" libvirt "libvirt"
    add_user_to_group_if_available "${USERNAME}" kvm "KVM"
  else
    log_info "libvirt no instalado; no se modifican grupos libvirt/kvm."
  fi
}

verify_stage06_virtualization() {
  log_section "Virtualizacion"

  if target_command_exists_stage06 qemu-system-x86_64 || target_command_exists_stage06 virsh || target_command_exists_stage06 libvirtd; then
    log_kv "CPU virtualization" "$(detect_cpu_virtualization)"
    if [[ -e /dev/kvm ]]; then
      success "KVM disponible en /dev/kvm."
    else
      record_stage06_warning "qemu/libvirt parece instalado, pero /dev/kvm no existe en el Live ISO."
    fi
  else
    log_info "qemu/libvirt no detectado; se omite verificacion KVM."
  fi
}

verify_stage06_audio() {
  log_section "Audio"

  if target_command_exists_stage06 pipewire; then
    success "PipeWire instalado."
  else
    record_stage06_warning "PipeWire no parece instalado."
  fi
}

verify_stage06_base_identity() {
  local target_hostname
  local target_locale
  local target_keymap

  log_section "Verificacion locale/keymap/hostname"
  target_hostname="$(cat "$(target_path "${STAGE06_TARGET_ROOT}" /etc/hostname)" 2>/dev/null || true)"
  target_locale="$(awk -F= '$1 == "LANG" { print $2; exit }' "$(target_path "${STAGE06_TARGET_ROOT}" /etc/locale.conf)" 2>/dev/null || true)"
  target_keymap="$(awk -F= '$1 == "KEYMAP" { print $2; exit }' "$(target_path "${STAGE06_TARGET_ROOT}" /etc/vconsole.conf)" 2>/dev/null || true)"

  [[ "${target_hostname}" == "${HOSTNAME}" ]] || record_stage06_warning "Hostname esperado ${HOSTNAME}, detectado ${target_hostname:-vacio}."
  [[ "${target_locale}" == "${LOCALE}" ]] || record_stage06_warning "Locale esperado ${LOCALE}, detectado ${target_locale:-vacio}."
  [[ "${target_keymap}" == "${KEYMAP}" ]] || record_stage06_warning "Keymap esperado ${KEYMAP}, detectado ${target_keymap:-vacio}."

  log_kv "Hostname" "${target_hostname:-no detectado}"
  log_kv "Locale" "${target_locale:-no detectado}"
  log_kv "Keymap" "${target_keymap:-no detectado}"
}

show_stage06_summary() {
  local item
  local groups

  groups="$(arch_chroot_run "${STAGE06_TARGET_ROOT}" id -nG "${USERNAME}" 2>/dev/null || true)"

  log_section "Resumen final Stage06"
  log_kv "Usuario" "${USERNAME}"
  log_kv "Grupos" "${groups:-no detectados}"
  log_kv "Contrasena usuario" "${TARGET_USER_PASSWORD_STATUS:-verificada}"
  log_kv "Contrasena root" "${TARGET_ROOT_PASSWORD_STATUS:-omitida}"

  log_header "Servicios habilitados"
  if ((${#STAGE06_ENABLED_SERVICES[@]} == 0)); then
    log_info "Ninguno."
  else
    for item in "${STAGE06_ENABLED_SERVICES[@]}"; do
      log_kv "Servicio" "${item}"
    done
  fi

  log_header "Servicios omitidos"
  if ((${#STAGE06_OMITTED_SERVICES[@]} == 0)); then
    log_info "Ninguno."
  else
    for item in "${STAGE06_OMITTED_SERVICES[@]}"; do
      log_kv "Omitido" "${item}"
    done
  fi

  log_header "Advertencias"
  if ((${#STAGE06_WARNINGS[@]} == 0)); then
    log_info "Ninguna."
  else
    for item in "${STAGE06_WARNINGS[@]}"; do
      log_kv "Advertencia" "${item}"
    done
  fi

  success "Stage06 completado. Stage07 no se ejecutara automaticamente."
}

main() {
  log_section "Stage06 - System"
  require_root
  require_arch_live_iso
  require_uefi

  log_step "Cargando configuracion"
  load_install_config
  validate_install_config
  success "Configuracion cargada y validada."

  log_step "Cargando estado del target"
  load_stage06_install_state
  validate_arch_target_root "${STAGE06_TARGET_ROOT}"

  ensure_stage06_user
  configure_stage06_services
  configure_stage06_integrations
  verify_stage06_virtualization
  verify_stage06_audio
  verify_stage06_base_identity
  show_stage06_summary
}

main "$@"
